apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
   service: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 31000
    name: serving
  - port: 9300
    nodePort: 31003
    name: node-to-node
  selector:
    app: elasticsearch
