---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: fluentd
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  config.yaml: |-
    receivers:
      fluentforward:
        endpoint: 0.0.0.0:8006

    processors:
      batch:

    extensions:
      health_check:
      pprof:
      zpages:


    exporters:
      # file
      file:
        path: /logs/logs.json

      # logs
      logging:
        loglevel: debug

    service:
      extensions: [health_check, zpages, pprof]
      pipelines:
        logs:
          receivers: [fluentforward]
          processors: [batch]
          exporters: [file,logging]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: fluentd
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  - name: fluentd
    port: 8006
    protocol: TCP
    targetPort: 8006
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: fluentd
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib:latest
        name: otel-collector
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - mountPath: /etc/otel/config.yaml
          name: data
          subPath: config.yaml
          readOnly: true
        - mountPath: /logs
          name: logdir
      volumes:
        - name: data
          configMap:
            name: otel-collector-conf
        - name: logdir
          hostPath:
            path: /home/ranand/log-poc/fluentd/fluentd/logs