apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel
  namespace: otel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel
  namespace: otel
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otel
roleRef:
  kind: ClusterRole
  name: otel
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: otel
  namespace: otel
